# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ridealong' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ridealong
pod 'TB', :git => 'https://github.com/JonasDeichelmann/ToolBox.git'
pod 'RealmSwift'
pod 'Google/SignIn'
pod 'FacebookCore'
pod 'FacebookLogin'

  target 'RidealongTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RidealongUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
